name: Deploy Spring Boot Application

on:
  push:
    branches:
      - charitha  # Ensure this matches your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: mvn clean package

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: nexa-jar
          path: target/nexa-0.0.1-SNAPSHOT.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: nexa-jar
          path: ./nexa-0.0.1-SNAPSHOT.jar

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: ./nexa-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu/nexa-0.0.1-SNAPSHOT.jar

      - name: Restart Spring Boot Service
        uses: appleboy/ssh-action@v0.1.1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo systemctl daemon-reload
            sudo systemctl restart springboot-app
