name: Deploy Spring Boot Application

on:
  push:
    branches:
      - charitha

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      

      - name: Build with Maven
        run: mvn clean package

      - name: Deploy to EC2
        uses: appleboy/scp-action@v0.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: target/nexa-0.0.1-SNAPSHOT.jar
          target: /home/ubuntu/nexa-0.0.1-SNAPSHOT.jar

      - name: Restart Spring Boot Service
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_KEY }} ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          sudo systemctl restart springboot-app
          EOF
